# Generated by Django 4.1.13 on 2024-01-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_total_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=7, null=True
            ),
        ),
    ]
